// German Pokemon names (first 151 Pokemon in German)
const germanPokemonNames = [
	'Bisasam',
	'Bisaknosp',
	'Bisaflor',
	'Glumanda',
	'Glutexo',
	'Glurak',
	'Schiggy',
	'Schillok',
	'Turtok',
	'Raupy',
	'Safcon',
	'Smettbo',
	'Hornliu',
	'Kokuna',
	'Bibor',
	'Taubsi',
	'Tauboga',
	'Tauboss',
	'Rattfratz',
	'Rattikarl',
	'Habitak',
	'Ibitak',
	'Rettan',
	'Arbok',
	'Pikachu',
	'Raichu',
	'Sandan',
	'Sandamer',
	'Nidoran♀',
	'Nidorina',
	'Nidoqueen',
	'Nidoran♂',
	'Nidorino',
	'Nidoking',
	'Piepi',
	'Pixi',
	'Vulpix',
	'Vulnona',
	'Pummeluff',
	'Knuddeluff',
	'Zubat',
	'Golbat',
	'Myrapla',
	'Duflor',
	'Giflor',
	'Paras',
	'Parasek',
	'Bluzuk',
	'Omot',
	'Digda',
	'Digdri',
	'Mauzi',
	'Snobilikat',
	'Enton',
	'Entoron',
	'Menki',
	'Rasaff',
	'Fukano',
	'Arkani',
	'Quapsel',
	'Quaputzi',
	'Quappo',
	'Abra',
	'Kadabra',
	'Simsala',
	'Machollo',
	'Maschock',
	'Machomei',
	'Pudox',
	'Lektrobal',
	'Porenta',
	'Kleinstein',
	'Georok',
	'Geowaz',
	'Ponita',
	'Gallopa',
	'Flegmon',
	'Lahmus',
	'Magmar',
	'Pinsir',
	'Tauros',
	'Karpador',
	'Garados',
	'Lapras',
	'Ditto',
	'Evoli',
	'Aquana',
	'Blitza',
	'Flamara',
	'Porygon',
	'Amonitas',
	'Amoroso',
	'Kabuto',
	'Kabutops',
	'Aerodactyl',
	'Relaxo',
	'Arktos',
	'Zapdos',
	'Lavados',
	'Dratini',
	'Dragonir',
	'Dragoran',
	'Mewtu',
	'Mew'
];

/**
 * Generates a random Pokemon code consisting of 3 German Pokemon names
 * Format: "Glurak-Bisasam-Pikachu"
 */
export function generatePokemonCode(): string {
	const shuffled = [...germanPokemonNames].sort(() => Math.random() - 0.5);
	const selected = shuffled.slice(0, 3);
	return selected.join('-');
}

/**
 * Validates if a Pokemon code format is correct
 */
export function isValidPokemonCode(code: string): boolean {
	const parts = code.split('-');
	if (parts.length !== 3) return false;
	return parts.every((part) => germanPokemonNames.includes(part));
}
